### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by hiranthaR** [FOSS-UCSC/foss-ucsc.github.io#1]
Update readme

**Comment by Suvink** [comment]
Visit the website [https://foss-ucsc.github.io/](https://foss-ucsc.github.io/) and make a suitable readme file for the repository. You may use [StackEdit](https://stackedit.io/) to create this file. And use [Shields.io](https://shields.io/) to generate necessary shields. GIFs and other image assets can be used if necessary.
